#!/bin/sh

# mongod - Startup script for mongod
# chkconfig: 35 85 15
# description: Mongo is a scalable, document-oriented database.
# processname: mongod34

source /etc/init.d/functions
mongod="/mydata/local/mongodb34/bin/mongod34"
prog="mongod34"
mongod_conf="/mydata/local/mongodb34/mongod34.conf"

[ ! -f ${mongod_conf} ] && exit 5

pidfile="/mydata/local/mongodb34/${prog}.pid"
lockfile="/var/lock/subsys/${prog}"

start() {
    
    [ ! -x ${mongod} ] && exit 6
    echo -n "Starting ${prog}:"
    daemon ${mongod} --config ${mongod_conf} 2>/dev/null
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch ${lockfile}
    return $RETVAL

}




stop() {
    
    echo -n "Stopping ${prog}:"
    killproc -p ${pidfile} $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f ${lockfile}
    return $retval

}


restart() {

   stop
   start

}


case "$1" in
     start)
          status ${mongod} && exit 0
          $1
          ;;
     stop)
          status ${mongod} || exit 0
          $1
          ;;
      restart)
          $1
          ;;
      status)
          $1 ${mongod}
          ;;
      *)
          echo "Usage: ${0} {start|stop|status|restart}"
          exit 2
          ;;
 
  esac
